### PR TITLE
add error handling to startup logic

### PR DESCRIPTION
**Pull request by antondlr**
solves a couple issues on #238 : namely 
- provide default .env file if none provided
- better error handling on startup (i.e., APIs unavailable)

additionally, the final docker image is cleaner (less layers)

### CODE REVIEW

**Comment by antondlr** [comment]
example output of 
- BN connection not availabe
- VC connection available but wrong token provided

```
http://host.docker.internal:5052 unreachable, check settings and connection
validator api issue, server response: 403
```

**Comment by antondlr** [comment]
example output when no `.env` file found
```

No `/.env` file found at the expected location (`/app/.env`).
Please adapt this default file to your needs and mount it within the container:
----------------
PORT=3000
BACKEND_URL=http://127.0.0.1:3001
BEACON_URL=http://your-BN-ip:5052
VALIDATOR_URL=http://your-VC-ip:5062
API_TOKEN=get-it-from-'.lighthouse/validators/api-token.txt'
SESSION_PASSWORD="your-password"
SSL_ENABLED=true
----------------
```

**Comment by antondlr** [comment]
@chong-he 
are these startup-failures verbose enough for you to assist?

**Review by rickimoore — APPROVED** [review]
LGTM

**Pull request merged**
